updated

diff --git a/ready b/ready
--- a/ready
+++ b/ready
@@ -11,131 +11,188 @@ print_confirmation() {
     echo "$1 completed successfully."
 }
 
+# Function for updating package manager
+update_package_manager() {
+    sudo apt update || handle_error "Failed to update package manager"
+}
+
 # Ensure consistent indentation
 set -e
 trap 'handle_error "An error occurred"' ERR
 
-# Update package manager
-sudo apt update || handle_error "Failed to update package manager"
+# Function to install Docker
+install_docker() {
+    update_package_manager
+    if ! command -v docker &> /dev/null; then
+        sudo apt install -y docker.io || handle_error "Failed to install Docker"
+        sudo usermod -aG docker $USER || handle_error "Failed to add user to Docker group"
+        sudo chmod 666 /var/run/docker.sock || handle_error "Failed to set permissions for Docker socket"
+        print_confirmation "Docker installation"
+    else
+        echo "Docker is already installed"
+    fi
+}
 
-# Install Docker
-if ! command -v docker &> /dev/null; then
-    sudo apt install -y docker.io || handle_error "Failed to install Docker"
-    sudo usermod -aG docker $USER || handle_error "Failed to add user to Docker group"
-    sudo chmod 666 /var/run/docker.sock || handle_error "Failed to set permissions for Docker socket"
-    print_confirmation "Docker installation"
-else
-    echo "Docker is already installed"
-fi
+# Function to install Docker Compose
+install_docker_compose() {
+    update_package_manager
+    if ! command -v "docker compose" &> /dev/null; then
+        while true; do
+            echo "Do you want to install Docker Compose plugin(p) / Docker compose standalone(s) or skip it? (p/s/any key)"
+            read answer
 
-# Install Docker Compose
-if ! command -v "docker compose" &> /dev/null; then
-    while true; do
-        echo "Do you want to install Docker Compose plugin(p) / Docker compose standalone(s) or skip it? (p/s/any key)"
-        read answer
+            case "$answer" in
+                p)
+                    if ! command docker compose &> /dev/null; then
+                        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
+                        mkdir -p $DOCKER_CONFIG/cli-plugins
+                        curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose || handle_error "Failed to download Docker Compose plugin"
+                        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose || handle_error "Failed to set execute permission for Docker Compose plugin"
+                    else
+                        echo "Docker Compose plugin is already installed"
+                    fi
+                    print_confirmation "Docker Compose plugin installation"
+                    break
+                    ;;
+                s)
+                    if ! command docker-compose &> /dev/null; then
+                        sudo curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose || handle_error "Failed to download Docker Compose standalone"
+                        sudo chmod +x /usr/local/bin/docker-compose || handle_error "Failed to set execute permission for Docker Compose standalone"
+                    else
+                        echo "Docker Compose standalone is already installed"
+                    fi
+                    print_confirmation "Docker Compose standalone installation"
+                    break
+                    ;;
+                *)
+                    echo "Skipping Docker Compose installation."
+                    break
+                    ;;
+            esac
+        done
+    else
+        echo "Docker Compose is already installed"
+    fi
+}
 
-        case "$answer" in
-        p)
-            if ! command docker compose &> /dev/null; then
-                DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
-                mkdir -p $DOCKER_CONFIG/cli-plugins
-                curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose || handle_error "Failed to download Docker Compose plugin"
-                chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose || handle_error "Failed to set execute permission for Docker Compose plugin"
-            else
-                echo "Docker Compose plugin is already installed"
-            fi
-            print_confirmation "Docker Compose plugin installation"
-            break
+# Function to install Minikube
+install_minikube() {
+    update_package_manager
+    if ! command -v minikube &> /dev/null; then
+        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 || handle_error "Failed to download Minikube"
+        sudo install minikube-linux-amd64 /usr/local/bin/minikube || handle_error "Failed to install Minikube"
+        rm -rf minikube* || handle_error "Failed to clean up Minikube installation files"
+        print_confirmation "Minikube installation"
+    else
+        echo "Minikube is already installed"
+    fi
+}
+
+# Function to install kubectl
+install_kubectl() {
+    update_package_manager
+    if ! command -v kubectl &> /dev/null; then
+        sudo snap install kubectl --classic || handle_error "Failed to install kubectl"
+        print_confirmation "kubectl installation"
+    else
+        echo "kubectl is already installed"
+    fi
+}
+
+# Function to install net-tools
+install_net_tools() {
+    update_package_manager
+    if ! command -v ifconfig &> /dev/null; then
+        sudo apt install -y net-tools || handle_error "Failed to install net-tools"
+        print_confirmation "net-tools installation"
+    else
+        echo "net-tools is already installed"
+    fi
+}
+
+# Function to install programming languages and tools
+install_programming_languages() {
+    update_package_manager
+    sudo apt install -y golang clang llvm gcc-multilib libbpf-dev || handle_error "Failed to install programming languages and tools"
+    print_confirmation "Programming languages and tools installation"
+}
+
+# Function to install required tools
+install_required_tools() {
+    update_package_manager
+    sudo apt install -y make || handle_error "Failed to install make"
+    print_confirmation "make installation"
+}
+
+# Function to install bpftool
+install_bpftool() {
+    update_package_manager
+    kernel_version=$(uname -r)
+    sudo apt install -y linux-tools-$kernel_version || {
+        echo "Warning: Failed to install bpftool for kernel version $kernel_version"
+        return
+    }
+    print_confirmation "bpftool installation for kernel version $kernel_version"
+}
+
+
+# Function to install Zsh
+install_zsh() {
+    update_package_manager
+    if ! command -v zsh &> /dev/null; then
+        sudo apt install -y zsh || handle_error "Failed to install Zsh"
+        print_confirmation "Zsh installation"
+        exec zsh
+    else
+        echo "Zsh is already installed"
+    fi
+}
+
+# Function to display help message
+display_help() {
+    echo "Usage: $0 [-a] [-d] [-c] [-k] [-p] [-n] [-b] [-z] [-h]"
+    echo "Options:"
+    echo "  -a    Install all (Docker, Docker Compose, Minikube, kubectl, net-tools, programming languages, required tools, bpftool, Zsh)"
+    echo "  -d    Install Docker"
+    echo "  -c    Install Docker Compose"
+    echo "  -k    Install Minikube"
+    echo "  -p    Install kubectl"
+    echo "  -n    Install net-tools"
+    echo "  -b    Install bpftool"
+    echo "  -z    Install Zsh"
+    echo "  -h    Display this help message"
+}
+
+# Process flags
+while getopts ":adckpnbzh" opt; do
+    case ${opt} in
+        a)  install_docker
+            install_docker_compose
+            install_minikube
+            install_kubectl
+            install_net_tools
+            install_programming_languages
+            install_required_tools
+            install_bpftool
+            install_zsh
             ;;
-        s)
-            if ! command docker-compose &> /dev/null; then
-                sudo curl -SL https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose || handle_error "Failed to download Docker Compose standalone"
-                sudo chmod +x /usr/local/bin/docker-compose || handle_error "Failed to set execute permission for Docker Compose standalone"
-            else
-                echo "Docker Compose standalone is already installed"
-            fi
-            print_confirmation "Docker Compose standalone installation"
-            break
-            ;;
-        *)
-            echo "Skipping Docker Compose installation."
-            break
-            ;;
-        esac
-    done
-else
-    echo "Docker Compose is already installed"
+        d)  install_docker ;;
+        c)  install_docker_compose ;;
+        k)  install_minikube ;;
+        p)  install_kubectl ;;
+        n)  install_net_tools ;;
+        b)  install_bpftool ;;
+        z)  install_zsh ;;
+        h)  display_help ;;
+        \?) echo "Invalid option: -$OPTARG. Use -h for help." >&2
+            exit 1 ;;
+    esac
+done
+shift $((OPTIND -1))
+
+# Display help message if no flags are provided
+if [[ $# -eq 0 ]]; then
+    display_help
 fi
-
-# Install Minikube
-if ! command -v minikube &> /dev/null; then
-    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 || handle_error "Failed to download Minikube"
-    sudo install minikube-linux-amd64 /usr/local/bin/minikube || handle_error "Failed to install Minikube"
-    rm -rf minikube* || handle_error "Failed to clean up Minikube installation files"
-    print_confirmation "Minikube installation"
-else
-    echo "Minikube is already installed"
-fi
-
-# Install kubectl
-if ! command -v kubectl &> /dev/null; then
-    sudo snap install kubectl --classic || handle_error "Failed to install kubectl"
-    print_confirmation "kubectl installation"
-else
-    echo "kubectl is already installed"
-fi
-
-# Install net-tools
-if ! command -v ifconfig &> /dev/null; then
-    sudo apt install -y net-tools || handle_error "Failed to install net-tools"
-    print_confirmation "net-tools installation"
-else
-    echo "net-tools is already installed"
-fi
-
-# Install programming languages and tools
-sudo apt install -y golang clang llvm gcc-multilib libbpf-dev || handle_error "Failed to install programming languages and tools"
-print_confirmation "Programming languages and tools installation"
-
-# Install required tools
-sudo apt install -y make || handle_error "Failed to install make"
-print_confirmation "make installation"
-
-# Install bpftool
-sudo apt install -y linux-tools-5.15.0-84-generic || handle_error "Failed to install bpftool"
-print_confirmation "bpftool installation"
-
-# Install Zsh
-if ! command -v zsh &> /dev/null; then
-    sudo apt install -y zsh || handle_error "Failed to install Zsh"
-    sudo apt install -y curl wget git || handle_error "Failed to install curl, wget, git"
-    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || handle_error "Failed to install Oh My Zsh"
-    print_confirmation "Zsh installation"
-else
-    echo "Zsh is already installed"
-fi
-
-# Configure Zsh
-if ! grep -q "ZSH_THEME=\"avit\"" ~/.zshrc; then
-    echo '' >~/.zshrc
-    echo "ZSH_THEME=\"avit\"" >>~/.zshrc
-    echo "DEFAULT_USER=$USER" >>~/.zshrc
-    echo "plugins=(git zsh-autosuggestions zsh-syntax-highlighting)" >>~/.zshrc
-    echo "source \$ZSH/oh-my-zsh.sh" >>~/.zshrc
-    print_confirmation "Zsh configuration"
-else
-    echo "Zsh is already configured"
-fi
-
-# Install Zsh plugins
-if [ ! -d ~/.oh-my-zsh/plugins/zsh-syntax-highlighting ]; then
-    sudo git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/plugins/zsh-syntax-highlighting || handle_error "Failed to clone zsh-syntax-highlighting"
-fi
-
-if [ ! -d ~/.oh-my-zsh/plugins/zsh-autosuggestions ]; then
-    sudo git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/plugins/zsh-autosuggestions || handle_error "Failed to clone zsh-autosuggestions"
-fi
-
-print_confirmation "Zsh plugins installation"
 
 echo "All installations completed successfully."
